HotelFinder.UI/Models/ErrorViewModel.cs
using System;

namespace HotelFinder.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HotelFinder.UI/Controllers/HomeController.cs
using HotelFinder.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HotelFinder.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HotelFinder.UI/Controllers/HotelAddController.cs
using HotelFinder.DataAccess.DTO;
using HotelFinder.UI.APIService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelFinder.UI.Controllers
{
    public class HotelAddController : Controller
    {
        private readonly HotelAPIService _hotelAPIService;
        public HotelAddController(HotelAPIService hotelAPIService)
        {
            _hotelAPIService = hotelAPIService;
        }


        public IActionResult HotelAdd()
        {
             
            return View();
        }
        [HttpPost]
        public IActionResult HotelAdd( HotelDTO dto)
        {
           ViewBag.eklenenHorel= _hotelAPIService.HotelCreate(dto);
           return View() ;
        }
    }
}

HotelFinder.UI/Controllers/HotelDeleteController.cs
using HotelFinder.Entities;
using HotelFinder.UI.APIService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelFinder.UI.Controllers
{
    public class HotelDeleteController : Controller
    {
        private readonly HotelAPIService _hotelAPIService;
        public HotelDeleteController(HotelAPIService hotelAPIService)
        {
            _hotelAPIService = hotelAPIService;
        }
        public async Task< IActionResult> HotelDelete()
        {
             var Hotels = await _hotelAPIService.HotelListService();

             ViewBag.hotelList =  new SelectList(Hotels, "Id", "Name");

            return View();
        }
        [HttpPost]
        public IActionResult HotelDelete(int Id)
        {
            _hotelAPIService.HotelDelete(Id);

          return  RedirectToAction("HotelDelete");
        }
    }
}

HotelFinder.UI/Controllers/HotelFinderController.cs
using HotelFinder.Bussines.Abstract;
using HotelFinder.DataAccess.Abstract;
using HotelFinder.Entities;
using HotelFinder.UI.APIService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace HotelFinder.UI.Controllers
{
    public class HotelFinderController : Controller
    { 
        private readonly HotelAPIService _apiService;
        public HotelFinderController(  HotelAPIService aPIService)
        { 
            _apiService = aPIService;
        }
        public async Task<IActionResult> HotelList()
        {
                        
           ViewBag.HotelListAll= await _apiService.HotelListService();
            return View();
        }

        public IActionResult HotelAdd()
        {
            return View();
        }
    }
}

HotelFinder.UI/Controllers/HotelUpdateController.cs
using HotelFinder.Entities;
using HotelFinder.UI.APIService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Graph;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelFinder.UI.Controllers
{
    public class HotelUpdateController : Controller
    {
        private readonly HotelAPIService _hotelAPIService;
        public HotelUpdateController(HotelAPIService hotelAPIService)
        {
            _hotelAPIService = hotelAPIService;
        }
        public async Task<IActionResult> HotelUpdate()
        {
            ViewBag.hotellist = new SelectList(await _hotelAPIService.HotelListService(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult HotelUpdate(Hotel hotel)
        {
            
            _hotelAPIService.HotelUpdate(hotel);
            return View();
        }
    }

    
}

HotelFinder.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Merhaba</h1>
    <p><a>API Çalışma Sayıfasına Hoşgeldiniz. </a>.</p>
</div>

HotelFinder.UI/Views/HotelAdd/HotelAdd.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using HotelFinder.DataAccess.DTO
@model HotelDTO
<div class="container" >
    <form asp-action="HotelAdd" asp-controller="HotelAdd" method="post">
        <label> Otel Adı</label>
        <input type="text" asp-for="Name" />
        <label>Bulunduğu Şehir</label>
        <input type="text" asp-for="City"  />
        <input type="submit" value="Kaydet" class="btn btn-success" />

    </form>

</div>

HotelFinder.UI/Views/HotelDelete/HotelDelete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{  
}
@using HotelFinder.DataAccess.DTO
@model HotelDTO

<div class="container" >
    <form asp-action="HotelDelete" asp-controller="HotelDelete" method="post">
        <select asp-for="Id" asp-items="ViewBag.hotelList">
            <option value="value">Otel Seçiniz</option>
        </select>
        <input type="submit" value=" Kaydı Sil"  class="btn btn-info" />
    </form>

</div>

HotelFinder.UI/Views/HotelFinder/HotelList.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var hotels = (List<HotelFinder.Entities.Hotel>)ViewBag.HotelListAll;
}


<div class="container col-md-6 table table-striped">
    <table>
        <thead>
            <tr>
                <th>Otel Adı</th>
                <th>Şehir</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in hotels)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.City</td>
                </tr>

            }

        </tbody>

    </table>


</div>

HotelFinder.UI/Views/HotelUpdate/HotelUpdate.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<script src="sweetalert2.min.js"></script>
<link rel="stylesheet" href="sweetalert2.min.css">
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using HotelFinder.DataAccess.DTO
@model HotelDTO

<div class="container">
    <form asp-action="HotelUpdate" asp-controller="HotelUpdate" method="post">
        <select asp-items="ViewBag.hotellist" asp-for="Id">
            <option value="value">Güncellenecek Otel</option>
        </select>
        <br />
        <label>Otelin Yeni Adı</label>
        <input type="text" name="name" value="" asp-for="Name" />
        <label>Yeni Şehir</label> 
        <input type="text" name="City" value="" asp-for="City" />
        <input type="submit" name="name" value=" Güncelle" />
    </form>
   
</div>

HotelFinder.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hotel Listeleme</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HotelFinder'a Hoşgeldiniz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelFinder" asp-action="HotelList">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelDelete" asp-action="HotelDelete">Silme</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelAdd" asp-action="HotelAdd">Ekleme</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelUpdate" asp-action="HotelUpdate">Update</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 -Powered By Tevfik - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>